services:
  - type: web
    name: bewerbungs-ki-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        fromDashboard: true

